---
- name: Backup Database wordpress
  mysql_db:
    state: dump
    name: "{{ wordpress_mysql_database_name }}"
    target: "/tmp/{{ wordpress_backup_file }}.sql"
    login_user: "{{ wordpress_mysql_root_user }}"
    login_password: "{{ wordpress_mysql_root_pass }}"