---
- name: Change root document on apache2
  lineinfile:
    dest: /etc/apache2/sites-available/000-default.conf
    regexp: "DocumentRoot {{wordpress_doc_root}}"
    line: "        DocumentRoot {{ wordpress_root_path }}"
  notify: Restart apache2 service

- name: Create wordpress database
  mysql_db:
    name: "{{ wordpress_mysql_database_name }}"
    state: present
    login_user: "{{ wordpress_mysql_root_user }}"
    login_password: "{{ wordpress_mysql_root_pass }}"

- name: Copy wp-config template
  template:
    src: wp-config.php.j2
    dest: "{{ wordpress_root_path }}/wp-config.php"