---
- block: # Configure hostname
  - name: Configure hostname
    hostname:
      name: "{{ host_preparation_host_name }}"

  - name: Configure hosts file
    lineinfile:
      dest: /etc/hosts
      state: present
      regexp: "^{{ ansible_host }} "
      line: "{{ ansible_host }} {{ host_preparation_host_name }}"

  tags:
    - host-preparation-configure-hostname
