---
- block: # Performance Tuning
  - name: Configure security limits
    lineinfile:
      dest: /etc/security/limits.conf
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
    with_items: "{{ host_preparation_limits_vars }}"
    register: host_preparation_configure_security_limits

  - name: Configure sysctl.conf
    lineinfile:
      dest: /etc/sysctl.conf
      state: present
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
    with_items: "{{ host_preparation_sysctl_vars }}"
    register: host_preparation_configure_sysctl

  - name: Tuning hugepage
    lineinfile:
      dest: /etc/rc.local
      state: present
      insertbefore: ^exit 0$
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
    with_items: "{{ host_preparation_rc_vars }}"
    register: host_preparation_configure_hugepage

  - name: Check if server need to reboot
    set_fact:
      host_preparation_need_reboot: true
    when: |
      host_preparation_configure_security_limits.changed
      or host_preparation_configure_sysctl.changed
      or host_preparation_configure_hugepage.changed

  tags:
    - host-preparation-tuning
