---
- name: Configure authorized_key
  authorized_key:
    user: "{{ ansible_user }}"
    key: "{{ lookup('file', item) }}"
    state: present
    exclusive: yes
  with_first_found:
    - "{{ host_preparation_group_authorized_keys_path }}"
    - "{{ host_preparation_global_authorized_keys_path }}"
  tags:
    - host-preparation-configure-authorized_keys
    - host-preparation-configure-user

# Need this fix
# http://thornelabs.net/2014/04/01/ansible-fix-colon-syntax-error-for-sudoers-file.html
- name: Configure sudoer file to not ask for password when use sudo
  lineinfile:
    "dest=/etc/sudoers
    state=present
    regexp='^%sudo\tALL='
    line='%sudo\tALL=(ALL:ALL) NOPASSWD: ALL'
    validate='visudo -cf %s'"
  tags:
    - host-preparation-configure-user

- name: Delete password from logged in user
  command: passwd -d {{ ansible_user }}
  tags:
    - host-preparation-configure-user
